language: node_js
node_js:
  - "0.10"
before_script:
  - chmod +x ./deploy.sh
  - npm run build
script:
  - ./deploy.sh
env:
  global:
    - GH_REF: github.com/derekr/photo-viewer-3000.git
    - secure: CBk/arSDmSKmbzUdyhC6xiqq2GPXtn6opT9jm5ibaHoTfFSnPWOmgMB6Wit9q1wJnoYz9bqd6UOO+e9cbb2pFpp2UgLDFgaHWfVNPEUKpfWbkIvy3I2+i4oDbk5SRHKupNHtlZ4LBIEBGfAi4ENB45nIoKgjsH6BeN/0P2fJdwQ=
